# Generated by Django 3.1 on 2021-01-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210113_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_overview', models.CharField(max_length=2000)),
                ('languages', models.CharField(choices=[('J', 'JavaScript'), ('H', 'HTML5'), ('C', 'CSS3'), ('P', 'Python'), ('S', 'SQL'), ('M', 'MongoDB')], max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='developer',
            name='projects',
        ),
        migrations.AddField(
            model_name='developer',
            name='projects',
            field=models.ManyToManyField(to='main_app.Project'),
        ),
    ]
